druid:
  master:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&connectTimeout=10000&socketTimeout=2000
    username: root
    password: 123456
    filters: stat
    maxActive: 80
    initialSize: 10
    maxWait: 1000
    minIdle: 20
    minEvictableIdleTimeMillis: 30000
    validationQuery: "select 1"
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 60
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: false
    keepAlive: true
  slave:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/my_demo?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&connectTimeout=10000&socketTimeout=2000
    username: root
    password: 123456
    filters: stat
    maxActive: 80
    initialSize: 10
    maxWait: 1000
    minIdle: 20
    minEvictableIdleTimeMillis: 30000
    validationQuery: "select 1"
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 60
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: false
    keepAlive: true

mybatis:
  internal:
    mapperLocations: "classpath:mappers/*.xml"

dubbo:
  application:
    name: demo-provider # 服务名
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
  protocol:
    name: dubbo # 指定通信协议
    port: 20881 # 通信端口  这里指的是与消费者间的通信协议与端口
    threads: 30
  provider:
    timeout: 10000 # 配置全局调用服务超时时间，dubbo默认是1s，肯定不够用呀
    retries: 3 # 重试3次
    delay: -1

